/*
 * SHA-256 and HMAC-SHA256, written out here rather than taken from a library.
 *
 * Two reasons, and neither is "not invented here":
 *
 * 1. A provably fair game's verifier has to run in the player's hands. The
 *    server uses node:crypto, the browser has SubtleCrypto, and the two have
 *    different APIs and different async-ness - so a shared implementation is
 *    the only way the house and the player can be running literally the same
 *    arithmetic. If they run different code, "provably fair" is a promise
 *    rather than a proof.
 *
 * 2. It has to be synchronous. SubtleCrypto is promise-based, which would put
 *    an await inside the outcome derivation, which would put it inside the
 *    round transaction. Money code with an await in the middle of it is how
 *    half-settled rounds happen.
 *
 * Checked against the published FIPS-180-4 and RFC-4231 vectors in
 * sha256.test.ts. Do not edit this file without running that.
 */

const K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4, 0xab1c5ed5,
  0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174,
  0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967,
  0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85,
  0xa2bfe8a1, 0xa81a664b, 0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
  0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
])

const rotr = (x: number, n: number) => (x >>> n) | (x << (32 - n))

const BLOCK = 64

export function sha256(msg: Uint8Array): Uint8Array {
  const h = new Uint32Array([
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
  ])

  /* One 0x80 byte, then zeroes, then the length as a big-endian 64-bit count of
   * bits - padded up to whole blocks. */
  const padded = new Uint8Array(Math.ceil((msg.length + 9) / BLOCK) * BLOCK)
  padded.set(msg)
  padded[msg.length] = 0x80

  const view = new DataView(padded.buffer)
  const bits = msg.length * 8
  view.setUint32(padded.length - 8, Math.floor(bits / 0x100000000))
  view.setUint32(padded.length - 4, bits >>> 0)

  const w = new Uint32Array(64)

  for (let off = 0; off < padded.length; off += BLOCK) {
    for (let i = 0; i < 16; i++) w[i] = view.getUint32(off + i * 4)
    for (let i = 16; i < 64; i++) {
      const a = w[i - 15]
      const b = w[i - 2]
      const s0 = rotr(a, 7) ^ rotr(a, 18) ^ (a >>> 3)
      const s1 = rotr(b, 17) ^ rotr(b, 19) ^ (b >>> 10)
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) >>> 0
    }

    let a = h[0]
    let b = h[1]
    let c = h[2]
    let d = h[3]
    let e = h[4]
    let f = h[5]
    let g = h[6]
    let hh = h[7]

    for (let i = 0; i < 64; i++) {
      const s1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)
      const ch = (e & f) ^ (~e & g)
      const t1 = (hh + s1 + ch + K[i] + w[i]) >>> 0
      const s0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)
      const maj = (a & b) ^ (a & c) ^ (b & c)
      const t2 = (s0 + maj) >>> 0

      hh = g
      g = f
      f = e
      e = (d + t1) >>> 0
      d = c
      c = b
      b = a
      a = (t1 + t2) >>> 0
    }

    h[0] = (h[0] + a) >>> 0
    h[1] = (h[1] + b) >>> 0
    h[2] = (h[2] + c) >>> 0
    h[3] = (h[3] + d) >>> 0
    h[4] = (h[4] + e) >>> 0
    h[5] = (h[5] + f) >>> 0
    h[6] = (h[6] + g) >>> 0
    h[7] = (h[7] + hh) >>> 0
  }

  const out = new Uint8Array(32)
  const outView = new DataView(out.buffer)
  for (let i = 0; i < 8; i++) outView.setUint32(i * 4, h[i])
  return out
}

export function hmacSha256(key: Uint8Array, msg: Uint8Array): Uint8Array {
  const shortened = key.length > BLOCK ? sha256(key) : key

  const inner = new Uint8Array(BLOCK + msg.length)
  const outer = new Uint8Array(BLOCK + 32)
  for (let i = 0; i < BLOCK; i++) {
    const k = i < shortened.length ? shortened[i] : 0
    inner[i] = k ^ 0x36
    outer[i] = k ^ 0x5c
  }
  inner.set(msg, BLOCK)
  outer.set(sha256(inner), BLOCK)

  return sha256(outer)
}

/* ------------------------------------------------------------- plumbing */

const HEX = '0123456789abcdef'

export function toHex(bytes: Uint8Array): string {
  let s = ''
  for (const b of bytes) s += HEX[b >> 4] + HEX[b & 15]
  return s
}

export function fromHex(hex: string): Uint8Array {
  if (hex.length % 2 !== 0) throw new Error(`odd-length hex: ${hex.length} chars`)
  const out = new Uint8Array(hex.length / 2)
  for (let i = 0; i < out.length; i++) {
    const byte = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16)
    if (Number.isNaN(byte)) throw new Error(`not hex: ${hex.slice(i * 2, i * 2 + 2)}`)
    out[i] = byte
  }
  return out
}

const encoder = new TextEncoder()
export const utf8 = (s: string): Uint8Array => encoder.encode(s)

export const sha256Hex = (s: string): string => toHex(sha256(utf8(s)))
export const hmacHex = (key: string, msg: string): string => toHex(hmacSha256(utf8(key), utf8(msg)))
